name: TimeReward
authors: [DevilishDante]
version: '2.0'
api-version: 1.16
main: fr.devilishdante.ecaerios.TimeReward.TrCore
commands:
  TimeReward:
    description: "commande principale"
    aliases: [tr]